### ISSUE TITLE
Avoid naming local variables like that

### ISSUE THREAD

**Issue by AlexKap23** [Sosa09/HangMan#1]
https://github.com/Sosa09/HangMan/blob/6ca4a8c6eb5e44d9fb45c163812bc73e201ddd92/HangMan/Program.cs#L36-L39

Using an underscore prefix for local variables within a method is not a common practice in C#. Local variables are typically named using camelCase without any special prefixes. The underscore prefix is generally reserved for private fields within a class.

**Comment by Sosa09** [comment]
Corrected all localvariable naming that were having an underscore as first index.
